sbcl-git:
- When <PKG_DB_TMPDIR>/+CONTENTS exists, set PKGREVISION by parsing the
  previous PKGREVISION from that file. Otherwise, set PKGREVISION in a
  format similar to that used in git-package.mk, but using a narrower
  timestamp resolution. In the former case, this should serve to allow
  for some builds to be resumed without 'make clean', and without
  manually setting PKGREVISION from the cmdline. In the latter case,
  this should serve to diffentiate between different builds produced in
  the same day (UTC) but with differing upstream HEAD revisions --
  moreover, without requiring access to a Git repository, in order to
  determine the appropriate PKGREVISION.

- Patch make.sh to not overwrite any existing build-config. This serves
  to ensure that make-config.sh will be run exactly once, during
  the build. As such, the SBCL_BUILD_OPTIONS will now be specified only
  to make-config.sh in do-configure

- Add support for building/installing the sbcl-internals texinfo manual;
  update PLIST

- Merge info-make calls into a new do-docs-build tgt.

- Update annotations - versioning

- Update distinfo for the make.sh patch

diff --git a/sbcl-git/Makefile b/sbcl-git/Makefile
--- a/sbcl-git/Makefile
+++ b/sbcl-git/Makefile
@@ -33,22 +33,50 @@ GIT_REPO.sbcl=		git://git.code.sf.net/p/sbcl/sbcl
 ##   between the version in DISTNAME and the version as distributed.
 ##
 ## Notes:
-## - The version provided in PKGNAME is now being automatically updated
-##   as per git-package.mk, such that presently derives a package
-##   version number from the latest changeset date. Thus, any subsequent
-##   builds of this package - aross any upstream source updates - should
-##   be produced with a monotonically increasing package name, as
-##   presently.
-##
-## - This does not entail any process for computing any mk-file
-##   variables directly from version.lisp-expr - a build system file,
-##   such that will not be available until after the configure tgt,
-##   defined below.
+## - There is a further description provided about this value's expected
+##   usage, below.
 ##
 SBCL_PATCHVERSION=	1.5.6
 
 .include "../../mk/bsd.prefs.mk"
 .include "../../wip/mk/git-package.mk"
+
+
+.if exists(${WRKDIR}/.pkgdb/+CONTENTS)
+## Unparse and reuse the previous PKGREVISION
+##
+## This should serve to ensure that some interrupted 'make install'
+## can be resumed, assuming that the +CONTENTS file has been created by
+## the time when the 'make install' failed or was interrupted. If not,
+## the build should be cleaned before restarting, or the original
+## PKGREVISION specified on the cmdline.
+##
+## FIXME: Save the PKGREVISION at the start of the build, using a unique
+## cookie filename uner WRKDIR
+##
+## NB: This script in itself may not be able to use PKG_DB_TMPDIR for
+## purposes of pathname reference. That variable is typically set within
+## pkgsrc mk/pkgformat/pkg/metadata.mk and may not have been set, when
+## this expression is evaluated as a shell script. It's assumed here
+## that that value will not have been changed to any other value, within
+## any site mk-file expressions.
+##
+_SB_REUSE_PKGREV_CMD=${GREP} '^@name' ${WRKDIR}/.pkgdb/+CONTENTS | \
+	${AWK} '{print $$2}' | ${SED} 's|^${PKGNAME_NOREV}${NBPAX_PROGRAM_PREFIX}||'
+PKGREVISION=${_SB_REUSE_PKGREV_CMD:sh}
+.else
+## Use a finer resolution for the date-oriented PKGREVISION string,
+## such that the PKGREVISION will differ across any two pkg builds
+## within a day's duration (UTC) and will be monotonically increasing,
+## between any earlier build and any later - assuming that both builds
+## were not begun within the same minute, on the system clock.
+##
+## This should serve to ensure that two builds for different upstream
+## changesets, on the same day, will not be built under the same PKGNAME,
+## while not requiring access to the source repository, if in order to
+## produce the initial PKGREVISION string.
+_GIT_PKGVERSION_CMD:=	${DATE} -u +'%Y.%m.%dT%H%M'
+.endif
 
 USE_TOOLS+=		gmake gtar:run patch
 
@@ -117,72 +145,132 @@ SBCL_BUILD_OPTIONS+=	--without-${OPT}
 .endfor
 
 .if !empty(PKG_OPTIONS:Mdoc)
-SBCL_BUILD_DOCS=	true
-INFOFILES+=		${WRKSRC}/doc/manual/*.info ${WRKSRC}/doc/manual/*.info-*
+INFOFILES+=		${WRKSRC}/doc/manual/*.info ${WRKSRC}/doc/manual/*.info-[1-9]*
+INFOFILES+=		${WRKSRC}/doc/internals/*.info ${WRKSRC}/doc/internals/*.info-[1-9]*
+## PERL and graphviz (dot) will be needed for 'make info' in doc/internals/
+USE_TOOLS+=		perl
+TOOL_DEPENDS+=		graphviz-[0-9]*:../../graphics/graphviz
 
-do-remove-info-dir: .PHONY
-	rm -f ${DESTDIR}${PREFIX}/share/info/dir
+do-docs-build: .PHONY ## NB: needs 'build' as an implicit prereq
+	${GMAKE} -C ${WRKSRC}/doc/manual/ info MAKEINFO=${MAKEINFO}
+	${GMAKE} -C ${WRKSRC}/doc/internals/ info MAKEINFO=${MAKEINFO}
 .else
-do-remove-info-dir: .PHONY
+do-docs-build: .PHONY
 .endif
 
-## NB - also in pre-confgure
+## NB - A synopsis for the following
+##
+## In pre-configure:
 ## - Patch make-config.sh to not re-run generate-version.sh
-##   when version.lisp-expr exists
+##   when the file version.lisp-expr exists
 ##
-## Then, in do-configure
-## - Run generate-version.sh (via make-config.sh)
+## Then, in do-configure:
+## - Run generate-version.sh once (via make-config.sh)
 ##
-## Subsq, in post-configure
-## - Trim the '-dirty' flag from version.lisp-expr - using subst classes -
-##   assuming the patches do not modify anything under SBCL 'src'
-## - Verify corresondance between SBCL_PATCHVERSION, or fail with error.
+## Subsequently, in post-configure:
+## - Trim the '-dirty' flag from version.lisp-expr, using subst classes.
+##   Assuming that the patches applied in this port will not modify
+##   any souce files under SBCL 'src', the '-dirty' flag may appear
+##   misleading, for some purposes of systems review.
+##
+## - Verify corresondance between the version in the locally available
+##   source repository and SBCL_PATCHVERSION, or fail with error.
 ##   The error message would indicate any version-mismatch. In case of
-##   version mistmatch, this Makefile should be updated (please see above)
+##   version mistmatch, this port should be updated, in at least to
+##   provide a 'Version bump' at SBCL_PATCHVERSION
 ##
-## This endeavors to work around the dependency circle introduced if we'd
-## try to produce a package version number from SBCL version.lisp-expr.
+## This endeavors to work around the dependency issues that would be
+## introduced, in either of two alternate approaches for the versioning
+## of this pkg:
 ##
-## At present, the version number in PKGNAME will be derived from the
-## latest changeset in the local git repository - whereas the version
-## number in DISTNAME will provide a consistent version number across a
-## certain series of changesets, by in large independent to the Git
-## repository itself.
-
-## NB: make-config.sh is now being run twice, once during
-## configure, and once when it's run by make.sh during build.
+## 1. If we'd try to produce a package version number from the SBCL
+##    build file, version.lisp-expr, or
+## 2. If we'd try to produce a package version number more directly
+##    derived from the Git repository information, itself. Such
+##    information may not be immediately available in the pkgsrc ports
+##    system, at some times of when the pkg build is begun.
 ##
-## Should this prove to be a concern, SBCL make.sh may be patched
-## to not re-run make-config.sh when the respective build configuration
-## files have already been produced by an earlier make-config.sh [FIXME]
+## In either instance, the resulting derived version may not match
+## that which would have been derived before the corresponding stage in
+## the build process - respectively, as in regards to the 'configure'
+## and earlier 'extract' stages, in the build.
+##
+## If this approach to versioning may not be sufficient for all
+## applications, perhaps it may be feasible to store a persistent version
+## number under ./files/ such that the version number would have been
+## derived directly from the Git source repository for SBCL - in a
+## manner no doubt analogous to the behaviros of SBCL's build script,
+## generate-version.sh
+##
+## For support of any specifically tagged release of SBCL, GIT_TAG.sbcl
+## may be defined locally in mk.conf
+##
+## ----
+##
+## About versioning in this pkg:
+##
+## - The PKGREVISION string will be derived as representative of a
+##   timestamp at which the build was begun. If CHECKOUT_DATE.sbcl
+##   was defined in the build, alternately, the PKGREVISION would
+##   reflect that timestamp.
+##
+## - The version number in PKGNAME - in effect, the concatenation of
+##   PKGVERSION_NOREV, the 'nb' qualifier, and the PKGREVISION string -
+##   this version number will include, as a substring, the value of
+##   SBCL_PATCHVERSION. This, of course, may not match the value
+##   returned by lisp-implementation-version when evaluated in the
+##   resutling SBCL build, It will provide a monotonicaly increasing
+##   package version, for subsequent package builds - assuming a
+##   duration of at least one minute, between subsequent package builds.
+##
+## - The version number PKGNAME_NOREV will be derived from the
+##   SBCL_PATCHVERSION for the build. As such, the expression
+##       ${PKGVERSION_NOREV} == ${SBCL_PATCHVERSION}
+##   typically evalutes as true.
+##
+## - The version number SBCL_PATCHVERSION will provide a consistent
+##   version number, across a certain series of changesets, by in large
+##   independent of the Git repository or the build system. This version
+##   can be considered to apply to the port from which the pkg is built.
+##
+## - The version number returned by the function lisp-implementation-version,
+##   when evaluated in the resulting SBCL build, may be considered to represent
+##   the normative version identifier for that SBCL distribution. It
+##   should match SBCL_PATCHVERSION in the complete substring
+##   represented as the value of the latter.
 
 do-configure:
-	cd ${WRKSRC} && env CC=${CC} GNUMAKE=${GMAKE} ${SH} make-config.sh --prefix=${PREFIX} --xc-host=${SBCL_BOOT_SYSTEM:Q} ${SBCL_BUILD_OPTIONS}
+	cd ${WRKSRC} && ${PKGSRC_SETENV} CC=${CC} GNUMAKE=${GMAKE} ${SH} \
+	  make-config.sh --prefix=${PREFIX} --xc-host=${SBCL_BOOT_SYSTEM:Q} ${SBCL_BUILD_OPTIONS}
 
 post-configure:
 	@SRC_VERSION=$$(${TAIL} -n1 ${WRKSRC}/version.lisp-expr); \
 		VERSION=$$( ${ECHO} "$${SRC_VERSION}" | \
 		${SED} -e 's@"\([1-9][0-9]*\.[1-9][0-9]*\.[1-9][0-9]*\).*"@\1@g;' ); \
 	  if [ "$${VERSION}" != "${SBCL_PATCHVERSION}" ]; then \
-		echo "#-- ${PKGPATH}: Version Mismatch: Source patchlevel version $${VERSION} of $${SRC_VERSION} does not match ${SBCL_PATCHVERSION}" 1>&2; \
-		exit 1; else echo "#-- ${PKGPATH}: Build for source version $${SRC_VERSION}"; \
+	    echo "#-- ${PKGPATH}: Version Mismatch: Source patchlevel version $${VERSION} of $${SRC_VERSION} does not match ${SBCL_PATCHVERSION}" 1>&2; \
+	    echo "#-- ${PKGPATH}: Please update SBCL_PATCHVERSION" 1>&2; \
+	    exit 1; \
+          else echo "#-- ${PKGPATH}: Build for source version $${SRC_VERSION}"; \
 	  fi
 
 ## Primary Build, Install, Test
 
 do-build:
-	cd ${WRKSRC} && ${ENV} CC=${CC} GNUMAKE=${GMAKE} ${SH} make.sh --prefix=${PREFIX} --xc-host=${SBCL_BOOT_SYSTEM:Q} ${SBCL_BUILD_OPTIONS}
-post-build:
-	${TEST} -n "${SBCL_BUILD_DOCS}" && ${GMAKE} -C ${WRKSRC}/doc/manual/ info MAKEINFO=${MAKEINFO}
+	cd ${WRKSRC} && ${PKGSRC_SETENV} CC=${CC} GNUMAKE=${GMAKE} ${SH} make.sh
+post-build: do-docs-build
 	cd ${WRKSRC} && ${RM} -f contrib/sb-cover/test-output/*
 
-do-install: do-remove-info-dir
+do-install:
 	cd ${WRKSRC} && BUILD_ROOT=${DESTDIR} INSTALL_ROOT=${PREFIX} MAN_DIR=${PREFIX}/${PKGMANDIR} ${SH} install.sh
+	${TEST} -f ${WRKSRC}/doc/internals/sbcl-internals.info && \
+		${CP} ${WRKSRC}/doc/internals/sbcl-internals.info ${DESTDIR}${PREFIX}/share/info/
 	rm -f ${DESTDIR}${PREFIX}/lib/sbcl/asdf-install/installer.lisp.orig
 	rm -f ${DESTDIR}${PREFIX}/lib/sbcl/sb-posix/posix-tests.lisp.orig
 	rm -f ${DESTDIR}${PREFIX}/lib/sbcl/sb-posix/test-output/write-test.txt
 	rm -f ${DESTDIR}${PREFIX}/lib/sbcl/sb-posix/test-output/read-test.txt
 	rm -f ${DESTDIR}${PREFIX}/bin/sbcl.old ${DESTDIR}${PREFIX}/lib/sbcl/sbcl.core.old
+	rm -f ${DESTDIR}${PREFIX}/share/info/dir
 	find ${DESTDIR}${PREFIX}/lib/sbcl -type d -name CVS -exec rm -rf {} \+
 	find ${DESTDIR}${PREFIX}/lib/sbcl -type f -name .cvsignore -exec rm -f {} \+
 
